### ISSUE TITLE
Help VideoCall adapter

### ISSUE THREAD

**Issue by lordmen99** [synkers/quickblox-java-api#1]
Hi brother, can u help make videocall adapter quickblox?

**Comment by AdamGhani** [comment]
Hey lordmen99, could you point me to the docs for that? and further explain what you want to accomplish?

For now, I'm only implementing the Users module https://quickblox.com/developers/Users.

**Comment by lordmen99** [comment]
thx, for your respone. i just want make video call adapter where can i use and put with easy into my any app. U have some code u have been integration with ur own app?

**Comment by AdamGhani** [comment]
Sure. You could defnitely use their Android and iOS SDKs for that
https://quickblox.com/developers/Sample-webrtc-android
https://quickblox.com/developers/Sample-webrtc-ios

Hope that helps.

**Comment by lordmen99** [comment]
i have read that, its too many parameter. i have some code in 1 java file, to make test videocall. but still not working

**Comment by AdamGhani** [comment]
I advice that you use their SDK and not attempt to reinvent the wheel.

This project is a Java client that interacts with QB's REST API. If they had this client built, I wouldn't rebuild it from scratch.
